apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-registry
resources:
- namespace.yaml
- registry.yaml
- rbac.yaml
- build-workflow.yaml
- reset-registry-workflow.yaml
- configure-insecure-registry.yaml

configMapGenerator:
- name: static-files
  files:
  - files/redis-log.sh
  - files/redis.conf
  - files/redis.Dockerfile
  options:
    disableNameSuffixHash: true