apiVersion: v1
kind: ConfigMap
metadata:
  name: current-configmap
  namespace: sandbox
data:
  RAILS_ENV: "current"
  RACK_ENV: "current"
  REDIS_SESSION_SENTINEL_HOST: "host.orb.internal"
  REDIS_SESSION_WRITER_HOST: "master.ishiori-valkey.v1wvan.apne1.cache.amazonaws.com"
  REDIS_SESSION_WRITER_PORT: "6379"
  REDIS_SESSION_IS_ELASTICACHE: "false"
  REDIS_SIDEKIQ_SENTINEL_HOST: "host.orb.internal"
  REDIS_SIDEKIQ_WRITER_HOST: "master.ishiori-valkey.v1wvan.apne1.cache.amazonaws.com"
  REDIS_SIDEKIQ_WRITER_PORT: "6379"
  REDIS_SIDEKIQ_IS_ELASTICACHE: "false"
  REDIS_MISC_SENTINEL_HOST: "host.orb.internal"
  REDIS_MISC_WRITER_HOST: "master.ishiori-valkey.v1wvan.apne1.cache.amazonaws.com"
  REDIS_MISC_WRITER_PORT: "6379"
  REDIS_MISC_IS_ELASTICACHE: "true"
  KEYCLOAK_URL: "http://host.orb.internal:8080"

