apiVersion: v1
kind: ConfigMap
metadata:
  name: ec-configmap
  namespace: sandbox
data:
  RAILS_ENV: "nonclustermode"
  RACK_ENV: "nonclustermode"
  REDIS_SESSION_WRITER_HOST: "host.orb.internal"
  REDIS_SESSION_WRITER_PORT: "6370"
  REDIS_SIDEKIQ_WRITER_HOST: "host.orb.internal"
  REDIS_SIDEKIQ_WRITER_PORT: "6370"
  REDIS_MISC_WRITER_HOST: "host.orb.internal"
  REDIS_MISC_WRITER_PORT: "6370"
  KEYCLOAK_URL: "http://host.orb.internal:8080"

