apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sandbox

resources:
- namespace.yaml
- current-configmap.yaml
- demo-app-puma.yaml
- demo-app-puma-service.yaml
- demo-app-sidekiq.yaml
