apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth-sandbox
resources:
- namespace.yaml
- redis.yaml
- redis-second.yaml
- secret.yaml

configMapGenerator:
- name: static-files
  files:
  - files/redis-cluster-provision.sh
  - files/redis-sentinel-provision.sh
  - files/sentinel-notify.sh
  options:
    disableNameSuffixHash: true