apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workflows-sandbox
resources:
- namespace.yaml
- build-workflow.yaml

configMapGenerator:
- name: dockerfile
  files:
  - files/Dockerfile