global:
  domain: argocd.kube.ishiori.lnet 

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: ishiori-local-general-issuer
      cert-manager.io/common-name: argocd.kube.ishiori.lnet
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - argocd.kube.ishiori.lnet
    tls:
      - hosts:
        - argocd.kube.ishiori.lnet
        secretName: argocd-tls
  ingressGrpc:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: ishiori-local-general-issuer
      cert-manager.io/common-name: argocd.kube.ishiori.lnet
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    hosts:
      - argocd.kube.ishiori.lnet
    tls:
      - hosts:
        - argocd.kube.ishiori.lnet
        secretName: argocd-tls

configs:
  params:
    server.insecure: "true"
  cm:
    exec.enabled: "true"