apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: operations
resources:
- namespace.yaml
- opebox.yaml
- redisinsight.yaml

configMapGenerator:
- name: static-files
  files:
  - files/populate.py
  - files/redis_compare.py