---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-generator
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/reverseon/kubelocal-manifest.git
      revision: main
      directories:
        - path: "cluster-utilities/cert-manager"
        - path: "cluster-utilities/sealed-secrets"
        - path: "cluster-utilities/ingress-nginx"
        - path: "cluster-utilities/k8s-dashboard"
        - path: "cluster-utilities/argo-rollouts"
        - path: "cluster-utilities/cluster-scoped"
        - path: "cluster-utilities/cluster-registry"
        - path: "apps/sandbox"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/reverseon/kubelocal-manifest.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
# Special Application
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  project: default
  source:
    repoURL: https://github.com/reverseon/kubelocal-manifest.git
    targetRevision: main
    path: "cluster-utilities/argo-workflows"
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m