apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sidekiq-sandbox
resources:
- namespace.yaml
- redis.yaml
- secret.yaml
- sidekiq-trial-app.yaml

configMapGenerator:
- name: static-files
  files:
  - files/redis-cluster-provision.sh
  options:
    disableNameSuffixHash: true